### ISSUE TITLE
[bug] Dock led brightness setting doesn't work

### ISSUE THREAD

**Issue by GitPetri** [unfoldedcircle/bug-reports#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

- Open web configurator
- Go to a dock setting
- Set led brightness slider to any value
- Close dock setting
- Open dock setting
- Led brightness is back at default value 66 %

### How to Reproduce

1. Open web configurator
2. Go to a dock setting
3. Set led brightness slider to any value. It doesn't matter whether the new value is lower or higher than the default 66 %
4. Observe 'Change has been saved.' -message on UI
5. Close dock setting
6. Open dock setting
7. Led brightness is back at default value 66 %
<img width="401" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/33396519/b5e12d98-53f4-42a4-aab9-99e5e64da574">
<img width="407" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/33396519/2e6d53ab-e07b-459b-af35-7ef3fc1c67af">
<img width="402" alt="image" src="https://github.com/unfoldedcircle/feature-and-bug-tracker/assets/33396519/86cf5b1f-b96c-492b-b70c-b9e2c28a38fa">

### Expected behavior

Setting Led brightness value will set led brightness.

### System version

Dock 0.9.2

### What part of the system affected by the problem?

Web Configurator, Overall system

### Additional context

https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/51 might be related to this.

**Comment by zehnm** [comment]
The 66% is only a display issue: the configured value in the dock isn't read out yet. That will be fixed.

Setting the dock brightness value works however. Certain error notifications are still shown, even with brightness set to 0. This has been a design decision, but we will consider a "status LED off" setting, so it always remains dark.

**Comment by apgr** [comment]
0% works, but the other settings all seem very bright.  It is hard to see the difference

**Comment by GitPetri** [comment]
> 0% works, but the other settings all seem very bright. It is hard to see the difference

I think I saw the difference today (haven't had much time to play with the remote still) by booting up a dock, the initial led intensity was way higher that when the boot cycle ended so for me, yes looks like the 66% is just a display issue like @zehnm states above.

**Comment by zehnm** [comment]
Status update: fix has been released in the BETA group and will be released in the public OTA channel soon.

**Comment by zehnm** [comment]
Showing correct brightness setting is fixed in the just released version 1.6.4

**Comment by spl237** [comment]
This is not fixed. On my remote and dock, both with the latest firmware, changes to LED brightness in the configurator and the remote claim to have saved, but on returning to the screen are seen to still be the same.
