### ISSUE TITLE
Deleting a custom button from an IR dataset does not work in web-configurator

### ISSUE THREAD

**Issue by zucki** [unfoldedcircle/bug-reports#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It is not possible to remove a (custom) button from a ir dataset from a remote.
A delete button (x) in the UI is available but seems to have no effect.

### How to Reproduce

1. go to a remote in the Web-Configurator
2. open the IR data set with the edit button
3. try to delete a button from the list in the pop-up by click on the red X

### Expected behavior

By a click on the red X, the button should be removed from the ir dataset and the list in the UI.
Maybe an additional confirmation dialog pops up

### System version

v1.0.3

### What part of the system affected by the problem?

Web Configurator

**Comment by martonborzak** [comment]
Fixed in Release 1.1.0

**Comment by zucki** [comment]
@martonborzak After installing v1.1.0 and v1.1.1, the issue still exists for me

**Comment by martonborzak** [comment]
@zucki Have you tried hard refreshing your browser?

**Comment by zucki** [comment]
@martonborzak Thanks for the hint. "hard-refresh" or using a new browser session worked
