### ISSUE TITLE
Change of AC Temparature Fails

### ISSUE THREAD

**Issue by thomasknuchel** [unfoldedcircle/bug-reports#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When changing temperature on the remote, an error apears: invalid cmd_id: climate.target_temparatur. Valid commands: on, off, hvac_mode, target_temperature.

HA 2023.09.2, 
UCR: 1.2.1

### How to Reproduce

Select AC
Click on Plus or Minus

### Expected behavior

Exptedted result: AC updates target temperature.

**Comment by zehnm** [comment]
This _might_ be already fixed in the just released 1.3.3 version.
I'll verify it.

**Comment by F4Ck0R** [comment]
Can confirm that this is still an issue tested it with latest remote version 1.3.3 and HA 2023.10.1. It is independant if I connect my climate via HA Tado integration or Homekit to HA. In HA it works via RemoteTwo it doesn't. Thus I assume it's really a bug in the RemoteTwo HA integration.

By the way, would also be great if you could type in a number on te remote instead of repeatadly hitting + or - in case one clicks on the number showed on screen.

**Comment by zehnm** [comment]
Looks like the same error as https://github.com/unfoldedcircle/integration-home-assistant/issues/26

I'll check later this week when I'm back home.

@martonborzak doesn't the UI provide a "spinner or spinning wheel" for the temperature selection to avoid pressing +/-, or was that only in the old version? Unfortunately I don't have an AC unit for testing.

**Comment by zehnm** [comment]
Found it: it's an issue in the UI, which is sending the wrong command. We'll release a quick fix for °C unit soon. Support for °C / °F switching will follow.

**Comment by martonborzak** [comment]
There is a spinner. Drag up and down on the number and you can quickly change the temperature.

**Comment by zehnm** [comment]
Part of the BETA group release 1.4.0 and included in next public release.

**Comment by zehnm** [comment]
Fixed in 1.4.2
